# Generated by Django 5.2.8 on 2026-05-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotteetable',
            name='land',
            field=models.FloatField(),
        ),
    ]
