# Generated by Django 5.2.8 on 2026-05-11 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0002_alter_devotteetable_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amtperacre', models.IntegerField(db_default=1000)),
                ('amtpaid', models.IntegerField()),
                ('paid_date', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templeapi.devotteetable')),
            ],
        ),
    ]
