# Generated by Django 5.2.8 on 2026-05-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0003_payment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='paid_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
