# Generated by Django 5.2.8 on 2026-05-11 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0004_alter_payment_table_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='paid_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
