# Generated by Django 5.2.8 on 2026-05-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0005_alter_payment_table_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_table',
            name='paid_date',
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='amtpaid',
            field=models.CharField(max_length=1000),
        ),
    ]
