# Generated by Django 5.2.8 on 2026-05-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0006_remove_payment_table_paid_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_table',
            name='amtpaid',
        ),
        migrations.AddField(
            model_name='payment_table',
            name='amtpaiddetails',
            field=models.JSONField(default=[]),
        ),
    ]
