# Generated by Django 5.2.8 on 2026-05-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0007_remove_payment_table_amtpaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotteetable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='amtpaiddetails',
            field=models.JSONField(default=list),
        ),
    ]
