# Generated by Django 5.2.8 on 2026-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0008_alter_devotteetable_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='amtperacre',
            field=models.IntegerField(default=1000),
        ),
    ]
