# Generated by Django 5.2.8 on 2026-05-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0009_alter_payment_table_amtperacre'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_table',
            name='type',
            field=models.CharField(default='Acre', max_length=100),
        ),
    ]
