# Generated by Django 5.2.8 on 2026-05-15 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0010_payment_table_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentfortype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='type',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='templeapi.paymentfortype'),
        ),
    ]
