# Generated by Django 5.2.8 on 2026-05-15 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0011_paymentfortype_alter_payment_table_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_table',
            name='type',
        ),
    ]
