# Generated by Django 5.2.8 on 2026-05-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0012_remove_payment_table_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentfortype',
        ),
    ]
