# Generated by Django 5.2.8 on 2026-05-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapi', '0013_delete_paymentfortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='templeexpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comitteemember', models.CharField(max_length=100)),
                ('expensetype', models.CharField(max_length=100)),
                ('expenseamount', models.IntegerField()),
            ],
        ),
    ]
